### ISSUE TITLE
[DAP] Broken link in documentation

### ISSUE THREAD

**Issue by dandelion-lowcode** [eclipse-epsilon/epsilon#139]
https://github.com/eclipse-epsilon/epsilon/blob/fafe0ffeabb8c692792c3b750903643a8f300117/examples/org.eclipse.epsilon.examples.eol.dap/epsilon/README.md?plain=1#L17

**Comment by agarciadom** [comment]
Thank you for the catch! I forgot to update the README: I have just done that. This feature is now available from the official release of the vscode-epsilon extension in the Marketplace:

https://marketplace.visualstudio.com/items?itemName=SamHarris.eclipse-epsilon-languages
